name: Upload Python Package

on:
  release:
    types: [published]
  push:
    tags:
      - '*'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        os:
          - name: "ubuntu-24.04"
            platform: "linux"
            platform_id: "manylinux_x86_64"

          - name: "ubuntu-24.04-arm"
            platform: "linux"
            platform_id: "manylinux_aarch64"

          - name: "macos-14"
            platform: "macos"
            min_macos_version: "14"
            platform_id: "macosx_arm64"

          - name: "windows-2025"
            platform: "windows"
            platform_id: "win_amd64"

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Set up QEMU
        if: runner.os == 'Linux' && runner.arch == 'X64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.3.1
        env:
          CIBW_ENABLE: pypy
          CIBW_ARCHS_LINUX: ${{ runner.arch == 'X64' && 'auto ppc64le s390x' || 'auto armv7l' }}
          CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"
          CIBW_SKIP: "*t-*"
          CIBW_TEST_REQUIRES: tox
          CIBW_TEST_COMMAND: cd {project} && tox
          CIBW_TEST_SKIP: "*"
          CIBW_BUILD_VERBOSITY: 1

      - name: Store wheels
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os.name }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  publish:
    name: Publish to PyPI
    needs: build_wheels
    runs-on: ubuntu-latest

    steps:
      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          path: dist

      - name: Flatten dist directory
        run: |
          cd dist
          for i in *; do mv "$i"/*.whl . 2>/dev/null; rmdir "$i" 2>/dev/null; done

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Twine
        run: pip install twine

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
